# Generated by Django 5.2.6 on 2025-10-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField()),
                ('email', models.CharField()),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
